export const NOTIFY_USER = "NOTIFY_USER";
export const DISABLE_SLAMSWON_ON_ADD = "DISABLE_SLAMSWON_ON_ADD";
export const DISABLE_SLAMSWON_ON_EDIT = "DISABLE_SLAMSWON_ON_EDIT";
export const ALLOW_REGISTRATION = "ALLOW_REGISTRATION";
